pipeline {

    agent {
        label "AGENT-1"
    }

    environment{
        appVersion=""
        region='us-east-1'
        account="759713897143"
        project="roboshop"
        component="catalogue"
    }
    options{
        timeout(time: 30, unit: "MINUTES")
        disableConcurrentBuilds()
    }

    // parameters {
    //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    // }

    
    stages{

        stage('init'){
            steps{
                script{
                    withAWS(region:'us-east-1', credentials: 'aws-creds') {            
                        sh """
                        cd 00-vpc 
                        terraform init -reconfigure
                        """
                    }
                }
            }
        }
        stage('plan'){
            steps{
                script{
                    withAWS(region:'us-east-1', credentials: 'aws-creds') {            
                        sh """
                        cd 00-vpc 
                        terraform plan 
                        """
                    }
                }
            }
        }
        stage('apply'){
                input{
                    message'should we continue?'
                    ok 'Yes, we should.'
                    submitter 'alice bob'
                }
                steps{
                script{
                    withAWS(region:'us-east-1', credentials: 'aws-creds') {            
                        sh """
                        cd 00-vpc 
                        terraform apply 
                        """
                    }
                }
            }
        }
        stage('Trigger SG'){
            steps{
                script{
                   build job:"10-sg"
                    propagate: "false" // even if the SG fails VPC will not be affected
                    wait:"false"         // VPC will not wait for SG completion
                }
            }
        }

        
    }
    

    post{
        always{
            echo "I will always say hello again"
            deleteDir()
        }
        success{
            echo "Hello Success..."
        }
        failure{
            echo "Hello Failure..."
        }

    }
}